### ISSUE TITLE
Add a way to add ExUnit @moduletag and @tag attributes to generated test cases and tests

### ISSUE THREAD

**Issue by jbachhardie** [cabbage-ex/cabbage#29]
These features are very useful to define which tests to run in a specific situation through the exclude/include/only arguments to mix test. It would be good to be able to have some way of tagging the tests produced by cabbage, maybe through translating gherkin tags into ExUnit tags.

This might be already implemented but I can't find anything in the documentation.

**Comment by jbachhardie** [comment]
Okay, figured out you can add `@moduletag :tag` to the `*.exs` files, but it would still be better to have the gherkin tags translate into ExUnit tags so we can run/not run specific scenarios.

**Comment by mgwidmann** [comment]
Hmmm, yeah this is an interesting feature. I have added to automatically tag it as `:integration` (here https://github.com/cabbage-ex/cabbage/blob/master/lib/cabbage/feature.ex#L187) so thats one way in the mean time you can target them.

**Comment by mgwidmann** [comment]
Implementing in #34 ... see comment in #35
