### ISSUE TITLE
Different outputers

### ISSUE THREAD

**Issue by leifg** [cabbage-ex/cabbage#39]
Is there a way to output scenario results in a more detailed way? Ideally an outputer to HTML

**Comment by mgwidmann** [comment]
Cabbage is built on ExUnit, and it has formatters that you can use if you target only the cabbage tests using the `@integration` tag.
https://hexdocs.pm/ex_unit/ExUnit.Formatter.html

There are libraries I believe that will give you different output based on the tests that ran. Try looking here: https://hex.pm/packages?search=exunit&sort=recent_downloads
