### ISSUE TITLE
Document use of case templates

### ISSUE THREAD

**Issue by sadir** [cabbage-ex/cabbage#43]
Hi,

I am trying out your library and got stuck attempting to do:
```
use Cabbage.Feature, use: MyAwesomeTestCase, file: "my_feature.feature"
```
when I should have been using:
```
use Cabbage.Feature, template: MyAwesomeTestCase, file: "my_feature.feature"
```
A few words in the README to this effect would help others not to make my mistake!

**Comment by mgwidmann** [comment]
What made you think you should do `use: MyAwesomeTestCase`?  Is there somewhere in the documentation where thats done?

**Comment by sadir** [comment]
I saw it [here](https://github.com/cabbage-ex/cabbage/issues/3) when I was looking for the option.
