### ISSUE TITLE
Tests don't seem to run at all under 0.3.4

### ISSUE THREAD

**Issue by kerryb** [cabbage-ex/cabbage#45]
After upgrading Cabbage to 0.3.4, the features no longer seem to get executed. It looks like they're parsed, because I get the expected undefined step message if I remove a step definition, but the code in the step definitions isn't executed, and no tests are reported as having run.

(Elixir 1.5.1, Erlang/OTP 20, macOS 10.13)

**Comment by mgwidmann** [comment]
Yeah I noticed this morning as well. I've retired the package on hex and will try to get a fix out for it tonight.

**Comment by mgwidmann** [comment]
This has been fixed in `v0.3.5`!
