### ISSUE TITLE
Steps don't match in Elixir 1.7

### ISSUE THREAD

**Issue by kerryb** [cabbage-ex/cabbage#49]
### Environment
  * Cabbage 0.3.5
  * Elixir 1.7.1
  * Erlang/OTP 21.0

### Steps to reproduce

Create a new project, add cabbage and create a feature file with its associated test module. Run the test to get the "Please add a matching step" error. Paste the generated step definition into the test module.

### Expected behaviour

Test passes.

### Actual behaviour

Step definition is not found (the "Please add a matching step" error is shown again).

**Comment by hisapy** [comment]
I believe this issue can be closed
