### ISSUE TITLE
Help maintaining this library?

### ISSUE THREAD

**Issue by nicholasjhenry** [cabbage-ex/cabbage#51]
@mgwidmann would you like help to maintain this library? The team at @civilcode would be happy to take this on.

**Comment by mgwidmann** [comment]
Yes please, sorry I've been very busy with other things. What can I do to make that easier?

**Comment by mgwidmann** [comment]
I've added you as an admin maintainer. I'll need to still add you to publish releases on Hex

**Comment by mgwidmann** [comment]
Seems I cannot add you on Hex without your email. Find me on the elixir slack as `@mgwidmann` and we'll get that setup.

**Comment by nicholasjhenry** [comment]
Thank you very much, @mgwidmann. I've contacted you via my handle @nicholasjhenry.
