### ISSUE TITLE
Test this library it self

### ISSUE THREAD

**Issue by revati** [cabbage-ex/cabbage#57]
After having missing features I had to have to use this library, I forked it and added my required features (#34, #54, #55, #56).

I don't feel entirely safe with current tests.

It seems using `.feature` tests to test this package isn't most suitable to test package itself.

Maybe package itself should be tested with exunit. By somehow calling `.feature` tests and asserting CLI output? or I don't know.

Maybe actual test reads generated `.feature` test AST and asserts it?

Elixir `defdelegate` macro tests like [so](https://github.com/elixir-lang/elixir/blob/bbcc42c5cf7d9d7f8f0cb8fedd8b38987021c441/lib/elixir/test/elixir/kernel_test.exs#L503)

If we will be able to somehow solve this problem, I would be willing to become maintainer (if that is needed of course). 

Great job guys. Really cool project. 👍

**Comment by nicholasjhenry** [comment]
@revati I've added you as a collaborator as I'm not sure when I'll get to your PR's. Thank you for the contributions!
