### ISSUE TITLE
Tests produce warning

### ISSUE THREAD

**Issue by mgwidmann** [cabbage-ex/cabbage#6]
Running the tests with a clean `_build` folder produces the following warnings:

```
warning: this clause cannot match because a previous clause at line 1 always matches
  test/feature_test.exs:1

warning: this clause cannot match because a previous clause at line 1 always matches
  test/outline_test.exs:1
```

**Comment by rawkode** [comment]
Hi @mgwidmann,

I went to take a look at this, but couldn't replicate with Elixir 1.3 or 1.4

**Comment by mgwidmann** [comment]
I think the second one was fixed in https://github.com/cabbage-ex/gherkin/pull/5 and the other may have been cleaned up accidentally by another PR...

Thanks!
