### ISSUE TITLE
access

### ISSUE THREAD

**Issue by revati** [cabbage-ex/cabbage#60]
Hello, I would need access to `gherkin` repository as well, so I could create correct step suggestions when outlines are used.
And access to hexdocs documentation, so I could improve it.

Thanks

**Comment by nicholasjhenry** [comment]
@revati I have given you access to the Repo and will follow up with hex.

**Comment by revati** [comment]
Hello, got access for gherkin, but haven't received one for docs. Maybe it is because I had provided the wrong email in my profile. Can you please resend it?

**Comment by nicholasjhenry** [comment]
@revati I have now added you as an owner on hex for both cabbage and gherkin. If this resolves this issue, please close. Thanks!

**Comment by revati** [comment]
Thanks
