### ISSUE TITLE
API for `tag` definitions is terribly hacky

### ISSUE THREAD

**Issue by hauleth** [cabbage-ex/cabbage#78]
It uses terrible hack to allow syntax in form:

```
tag @foo do
  # …
end
```

Instead it should set tag value as a field in a `context` that is passed to the `setup` and force user to match on tags there. It would provide much nicer API and would de-cruft the implementation form hacks.

**Comment by revati** [comment]
Didnt quite catch. How is it hackey?

And what is your solution code wise?

**Comment by hauleth** [comment]
```elixir
setup ctx do
  if :foo in ctx.tags do
    # …
  end
end
```

The "hacky" part is that it does something different from what (I believe) most Elixir developers would expect it to do, which mean that:

```elixir
@foo "bar"

tag @foo do
  # …
end
```

Would define `setup` function for scenarios tagged with `@foo` not with `@bar`.

**Comment by revati** [comment]
I use them, but API is odd, for me more natural way would be

```
setup_tag :tag, _state do
  ...
end
```

So then it would be like so

- `setup_all` -> setup for test suite as a whole
- `setup` -> setup for each scenario (maybe even have alias `setup_scenario`)
- `setup_tag` -> setup some specific scenarios, where tag is provided. (provides ability to import those setups from other model)

I personally don't like the idea with `ifs` in `setup`, but it doesn't mean that such functionality should work out of the box as well, but shouldn't be considered as an idiomatic way of cucumber.

Doesn't it work already? As setup should get tags. Currently `tag` callbacks are executed within `setup` so it can somehow determine if that particular callback is applicable.

Please look into https://github.com/cabbage-ex/cabbage/issues/74
