### ISSUE TITLE
Behat-like usage

### ISSUE THREAD

**Issue by lud** [cabbage-ex/cabbage#81]
Hello,

In the PHP world (like it or not) there is Behat. With that tool, you define feature files and Feature context, but those are independant.

It means that in a feature file you can use "givens" and "thens" from any context.

With cabbage, you to define a feature file on top of your context. Is it on purpoe ? What would you think about implementing feature-independant contexts ?

**Comment by revati** [comment]
Hello, I am from PHP background as well ;)
I have used behat, but it was a few years ago.

I didn't quite catch your point. You can [import step](https://github.com/cabbage-ex/cabbage/blob/master/test/feature_import_test.exs#L24) implementations from different files.

**Comment by lud** [comment]
But then you have to create almost empty files just to import context. I was thinking about something more "automatic" for the user.

But at least this is enough for what I need, thank you, I missed it in the docs !

**Comment by revati** [comment]
If I understand you correctly, there are the following parts in behat:

- *context* - where one defines all context related steps
- *feature* - where one defines in what context it is and what `*.feature` file to use

*feature* can load steps from context and execute scenarios defined in `*.feature` file?

**Comment by lud** [comment]
Well IIRC there is no need to define the _feature_ part. You just write feature files and the Given/Then/When are available globally.

Maybe there is an option to restrict the contexts available to a particular feature, but I'm not sure.

**Comment by revati** [comment]
Global steps definition seems odd. At least how I use bdd. 
But I see value in defining all steps in context, and then all `*.feature` files are executed against specified context.

Maybe after 1.0
